### ISSUE TITLE
Hand reorders when you play cards

### ISSUE THREAD

**Issue by backjoob** [mdcurrie/dominion#17]
When you play cards, the cards in the hand sometimes (always?) reorder themselves.

**Comment by backjoob** [comment]
The game is selecting the first instance of a card and using that one instead of the clicked one. E.g.
Start with [Copper, Copper, Estate, Estate, Copper], 
Play the copper on the right
Hand becomes [Copper, Estate, Estate, Copper] because it played the leftmost Copper instead of the clicked Copper.

**Comment by RasPat1** [comment]
#33 Should take care of this.

**Comment by backjoob** [comment]
After the merge:

- it it appears to work with treasures.
- I still encountered some variation of this problem when playing a Market with multiple markets in hand. I played the right-most one, and the left-most one left my hand.
