### ISSUE TITLE
Passin in array of ids instead of a string to Game log

### ISSUE THREAD

**Issue by RasPat1** [mdcurrie/dominion#36]
ON starting a gam afer card selection
2 players
Only card selected was merchant.
This shows up in the console

react_devtools_backend.js:2430 Warning: Failed prop type: Invalid prop `game.log[0].ids` of type `array` supplied to `Game`, expected `string`.
    in Game (created by LoggedIn)
    in LoggedIn (created by App)
    in App
overrideMethod @ react_devtools_backend.js:2430
printWarning @ checkPropTypes.js:20
checkPropTypes @ checkPropTypes.js:82
validatePropTypes @ react.development.js:1875
createElementWithValidation @ react.development.js:2059
LoggedIn @ index.js:61
renderWithHooks @ react-dom.development.js:16260
updateFunctionComponent @ react-dom.development.js:18347
beginWork$1 @ react-dom.development.js:20176
beginWork$$1 @ react-dom.development.js:25756
performUnitOfWork @ react-dom.development.js:24695
workLoopSync @ react-dom.development.js:24671
performSyncWorkOnRoot @ react-dom.development.js:24270
(anonymous) @ react-dom.development.js:12199
unstable_runWithPriority @ scheduler.development.js:697
runWithPriority$2 @ react-dom.development.js:12149
flushSyncCallbackQueueImpl @ react-dom.development.js:12194
flushSyncCallbackQueue @ react-dom.development.js:12182
scheduleUpdateOnFiber @ react-dom.development.js:23709
dispatchAction @ react-dom.development.js:17076
socket.onmessage @ index.js:39
react_devtools_backend.js:2430 Warning: Failed prop type: Invalid prop `log[0].ids` of type `array` supplied to `Log`, expected `string`.
    in Log (created by Game)
    in Game (created by LoggedIn)
    in LoggedIn (created by App)
    in App
overrideMethod @ react_devtools_backend.js:2430
printWarning @ checkPropTypes.js:20
checkPropTypes @ checkPropTypes.js:82
validatePropTypes @ react.development.js:1875
createElementWithValidation @ react.development.js:2059
Game @ index.js:25
renderWithHooks @ react-dom.development.js:16260
mountIndeterminateComponent @ react-dom.development.js:18794
beginWork$1 @ react-dom.development.js:20162
beginWork$$1 @ react-dom.development.js:25756
performUnitOfWork @ react-dom.development.js:24695
workLoopSync @ react-dom.development.js:24671
performSyncWorkOnRoot @ react-dom.development.js:24270
(anonymous) @ react-dom.development.js:12199
unstable_runWithPriority @ scheduler.development.js:697
runWithPriority$2 @ react-dom.development.js:12149
flushSyncCallbackQueueImpl @ react-dom.development.js:12194
flushSyncCallbackQueue @ react-dom.development.js:12182
scheduleUpdateOnFiber @ react-dom.development.js:23709
dispatchAction @ react-dom.development.js:17076
socket.onmessage @ index.js:39
react_devtools_backend.js:2430 Warning: Failed prop type: The prop `score` is marked as required in `Score`, but its value is `null`.
    in Score (created by Game)
    in Game (created by LoggedIn)
    in LoggedIn (created by App)
    in App

**Comment by RasPat1** [comment]
These are prop type issues: Fixed in #37

**Comment by mdcurrie** [comment]
yay
